// <auto-generated />
using CoreBankerApi.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreBankerApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250110095425_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreBankerApi.Domain.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("IndustryId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AccountNumber = "1234567890",
                            IndustryId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            AccountNumber = "2345678901",
                            IndustryId = 2
                        },
                        new
                        {
                            CustomerId = 3,
                            AccountNumber = "3456789012",
                            IndustryId = 3
                        });
                });

            modelBuilder.Entity("CoreBankerApi.Domain.Models.Industry", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndustryId");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            IndustryId = 1,
                            Name = "Manufacturing"
                        },
                        new
                        {
                            IndustryId = 2,
                            Name = "Education"
                        },
                        new
                        {
                            IndustryId = 3,
                            Name = "Telecom"
                        });
                });

            modelBuilder.Entity("CoreBankerApi.Domain.Models.IndustryType", b =>
                {
                    b.Property<int>("IndustryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryTypeId"));

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndustryTypeId");

                    b.HasIndex("IndustryId");

                    b.ToTable("IndustryTypes");

                    b.HasData(
                        new
                        {
                            IndustryTypeId = 1,
                            IndustryId = 1,
                            Label = "Invoice Number",
                            Name = "Invoice Number"
                        },
                        new
                        {
                            IndustryTypeId = 2,
                            IndustryId = 1,
                            Label = "Quantity",
                            Name = "Quantity"
                        },
                        new
                        {
                            IndustryTypeId = 3,
                            IndustryId = 1,
                            Label = "Delivery Address",
                            Name = "Delivery Address"
                        },
                        new
                        {
                            IndustryTypeId = 4,
                            IndustryId = 2,
                            Label = "Invoice Number",
                            Name = "Invoice Number"
                        },
                        new
                        {
                            IndustryTypeId = 5,
                            IndustryId = 2,
                            Label = "Level",
                            Name = "Level"
                        },
                        new
                        {
                            IndustryTypeId = 6,
                            IndustryId = 2,
                            Label = "Course",
                            Name = "Course"
                        },
                        new
                        {
                            IndustryTypeId = 7,
                            IndustryId = 3,
                            Label = "GSM Number",
                            Name = "GSM Number"
                        },
                        new
                        {
                            IndustryTypeId = 8,
                            IndustryId = 3,
                            Label = "Network",
                            Name = "Level"
                        },
                        new
                        {
                            IndustryTypeId = 9,
                            IndustryId = 3,
                            Label = "Residential Address",
                            Name = "Course"
                        });
                });

            modelBuilder.Entity("CoreBankerApi.Domain.Models.Customer", b =>
                {
                    b.HasOne("CoreBankerApi.Domain.Models.Industry", "Industry")
                        .WithMany("Customers")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("CoreBankerApi.Domain.Models.IndustryType", b =>
                {
                    b.HasOne("CoreBankerApi.Domain.Models.Industry", "Industry")
                        .WithMany("IndustryTypes")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("CoreBankerApi.Domain.Models.Industry", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("IndustryTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
